apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-sample-app
  template:
    metadata:
      labels:
        app: ci-sample-app
    spec:
      containers:
      - name: ci-sample-app
        image: ci-sample-app:v1  # This matches the Docker image built in Jenkins
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ci-sample-app-service
spec:
  selector:
    app: ci-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
